#!/usr/bin/env python3
"""Block Edit/Write on files a generator owns.

Registered as a PreToolUse hook in .claude/settings.json.

WHY THIS EXISTS
---------------
On 2026-08-20, commit 63437c6 edited a generated notes page directly to remove a
duplicated block and left notes-data/ untouched. The page was correct and the
site looked fine. The next build_notes_pages.py run - which any nav edit
requires - would have silently restored the 143 deleted words.

The rule against that was already written in CLAUDE.md, in bold. It did not help,
because a rule only fires if the model happens to be thinking about it. This
fires every time.

CONTRACT
--------
stdin  : the PreToolUse JSON payload.
exit 0 : allowed, say nothing.
exit 2 : BLOCKED. stderr goes back to Claude as the reason.

Standard library only, like everything else that runs in this repo.
"""

import json
import pathlib
import re
import sys

# The 17 hand-written published pages. Derived, not guessed: this is what
# `python3 scripts/bake_templates.py` prints. Three of them live under
# revision-notes/, which is otherwise entirely generated.
HAND_WRITTEN = {
    "404.html", "about.html", "confirmation.html", "contact.html", "faq.html",
    "index.html", "marking.html", "privacy.html", "tutoring.html",
    "past-papers/index.html", "past-papers/aqa/index.html",
    "past-papers/edexcel/index.html", "past-papers/edexcel-b/index.html",
    "past-papers/ocr/index.html",
    "revision-notes/index.html",
    "revision-notes/macroeconomics-diagrams.html",
    "revision-notes/microeconomics-diagrams.html",
}

# path prefix -> (what owns it, what to edit instead)
GENERATED_TREES = [
    ("revision-notes/glossary/", "scripts/build_glossary.py",
     "glossary-data/ (curation.json or authored.json), then re-run it"),
    ("revision-notes/", "scripts/build_notes_pages.py",
     "the byte slice in notes-data/topics/<board>/<slug>.html, then re-run it"),
    ("practice-questions/", "scripts/build_questions.py",
     "questions-data/<board>/<spec>.json, then re-run it"),
    ("past-paper-questions/", "scripts/build_past_paper_questions.py",
     "past-paper-questions-data/, then re-run it"),
    ("flashcards/", "scripts/build_flashcards.py",
     "flashcards-data/<board>/<theme>.json, then re-run it"),
    ("sitemaps/", "scripts/build_sitemap.py",
     "nothing - re-run it AFTER committing the page edits"),
]

GENERATED_FILES = {
    "sitemap.xml": ("scripts/build_sitemap.py",
                    "nothing - re-run it AFTER committing the page edits"),
    "glossary-data/terms.json": ("scripts/extract_glossary.py",
                                 "the key-definition chip on the notes page it came from"),
    "past-paper-questions-data/taxonomy.json": ("scripts/build_past_paper_taxonomy.py",
                                                "the Edexcel topic records it is derived from"),
    "css/fontawesome-all.min.css": ("scripts/subset_fontawesome.py --apply",
                                    "the rule list in that stylesheet, then re-run the subsetter"),
    "webfonts/fa-solid-900.woff2": ("scripts/subset_fontawesome.py --apply",
                                    "_working/fontawesome/, then re-run the subsetter"),
}

# Machine-written by the Swift extractor and never hand-edited.
EXTRACTED = re.compile(r"^past-paper-questions-data/(edexcel-a|edexcel-a-as|aqa)/.+\.json$")


def verdict(rel: str):
    """Return (owner, edit_instead) if rel is generated, else None."""
    if rel in HAND_WRITTEN:
        return None
    if rel in GENERATED_FILES:
        return GENERATED_FILES[rel]
    if EXTRACTED.match(rel):
        return ("scripts/extract_past_paper_questions.swift",
                "nothing by hand - re-extract. tags.json is the hand-written half")
    for prefix, owner, instead in GENERATED_TREES:
        if rel.startswith(prefix):
            return (owner, instead)
    return None


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0                      # never block because the hook itself broke

    path = (payload.get("tool_input") or {}).get("file_path")
    if not path:
        return 0

    root = pathlib.Path(__file__).resolve().parent.parent.parent
    try:
        rel = pathlib.Path(path).resolve().relative_to(root).as_posix()
    except ValueError:
        return 0                      # outside the repo; not ours to police

    found = verdict(rel)
    if not found:
        return 0

    owner, instead = found
    print(
        f"BLOCKED: {rel} is generated by {owner}.\n"
        f"\n"
        f"Editing it here works until the next build, then the change is silently\n"
        f"reverted. That has already happened once on this repo (63437c6).\n"
        f"\n"
        f"Edit instead: {instead}\n"
        f"Then re-run the generator and `python3 scripts/verify_generated.py`.\n"
        f"\n"
        f"If this file really is meant to be hand-edited, the allowlist is\n"
        f"HAND_WRITTEN in .claude/hooks/block-generated.py, and\n"
        f"`python3 scripts/bake_templates.py` prints the authoritative list.",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
