#!/usr/bin/env python3
"""Generate past-paper-questions-data/taxonomy.json.

The past-paper question bank does not invent a topic taxonomy. It reuses the
one the site already publishes: the 87 Edexcel topic records in
questions-data/edexcel-theme-{1..4}/*.json, grouped by the UNITS dict in
build_questions.py, under the theme names taken from the notes index <h1>s.

Reusing those slugs verbatim means a past-paper topic URL is a pure function of
the matching notes URL, so the two can never drift and nothing has to be renamed
later.

Run:  python3 scripts/build_past_paper_taxonomy.py [--check]

--check validates and prints a summary without writing.

Standard library only, in keeping with the rest of scripts/.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_questions import UNITS, spec_key, unit_of  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_DATA = ROOT / "questions-data"
NOTES = ROOT / "revision-notes"
OUT = ROOT / "past-paper-questions-data" / "taxonomy.json"

QUALIFICATION = "A Level Economics A (9EC0)"

# Theme names lifted verbatim from the <h1> of each notes board index, so the
# question bank and the notes call the themes exactly the same thing.
THEMES = {
    1: "Introduction to Markets and Market Failure",
    2: "The UK Economy — Performance and Policies",
    3: "Business Behaviour and the Labour Market",
    4: "A Global Perspective",
}


def load_topics(theme):
    """Every topic record for one Edexcel theme, in spec order."""
    board_dir = f"edexcel-theme-{theme}"
    src = QUESTIONS_DATA / board_dir
    if not src.is_dir():
        sys.exit(f"missing {src} - is this branch based on main?")

    topics = []
    for path in sorted(src.glob("*.json")):
        d = json.loads(path.read_text(encoding="utf-8"))
        notes_rel = f"revision-notes/{board_dir}/{d['slug']}.html"
        if not (ROOT / notes_rel).is_file():
            sys.exit(f"{path.name}: notes page {notes_rel} does not exist")
        topics.append(
            {
                "spec": d["spec"],
                "slug": d["slug"],
                "title": d["title"],
                "shortTitle": d["shortTitle"],
                "notesUrl": f"/{notes_rel}",
                "questionsUrl": f"/practice-questions/{board_dir}/{d['slug']}.html",
            }
        )
    topics.sort(key=lambda t: spec_key(t["spec"]))
    return board_dir, topics


def build():
    themes = []
    seen_slugs = {}

    for theme in (1, 2, 3, 4):
        board_dir, topics = load_topics(theme)

        for t in topics:
            if t["slug"] in seen_slugs:
                sys.exit(f"duplicate slug {t['slug']} in {board_dir}")
            seen_slugs[t["slug"]] = t["spec"]

        units = []
        for unit_code in sorted({unit_of(t["spec"]) for t in topics}, key=spec_key):
            meta = UNITS.get((board_dir, unit_code))
            if meta is None:
                sys.exit(f"UNITS has no entry for ({board_dir}, {unit_code})")
            units.append(
                {
                    "unit": unit_code,
                    "name": meta[0],
                    "topics": [t for t in topics if unit_of(t["spec"]) == unit_code],
                }
            )

        themes.append(
            {
                "theme": theme,
                "slug": f"theme-{theme}",
                "name": THEMES[theme],
                "fullName": f"Edexcel Theme {theme}: {THEMES[theme]}",
                "notesIndexUrl": f"/revision-notes/{board_dir}/index.html",
                "notesDir": board_dir,
                "units": units,
            }
        )

    return {
        "qualification": QUALIFICATION,
        "board": "edexcel",
        "boardName": "Edexcel",
        "source": (
            "Generated by scripts/build_past_paper_taxonomy.py from "
            "questions-data/edexcel-theme-{1..4}/*.json and the UNITS dict in "
            "scripts/build_questions.py. Do not hand-edit."
        ),
        "themes": themes,
    }


def summarise(data):
    total = 0
    for th in data["themes"]:
        n = sum(len(u["topics"]) for u in th["units"])
        total += n
        print(f"  Theme {th['theme']}: {len(th['units'])} units, {n} topics")
    print(f"  total: {total} topics")
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate, write nothing")
    args = ap.parse_args()

    data = build()
    total = summarise(data)
    if total != 87:
        sys.exit(f"expected 87 Edexcel topics, found {total}")

    if args.check:
        print("check only - nothing written")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
